#pragma kernel CSMain

RWTexture2D<float4> weights;
RWTexture2D<float4> biases;

RWTexture2D<float4> Z;
RWTexture2D<float4> A;

int count;
int dispatchInc;

float Sum()
{
    return 0;
}

float ReLU(float4 x)
{
    return max(0.0f, x.r);
}

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    for (int i = 0; i < count; i = i + dispatchInc)
    {
        Z[int2(i, 0)] = Sum() + biases[int2(i, 0)];
        A[int2(i, 0)].r = ReLU(Z[int2(i, 0)]);
    }
}